In [1]:
import numpy as np

# Create Numpy Array as List

In [2]:
np.array([1, 2, 3, 4])

array([1, 2, 3, 4])

In [3]:
a1 = np.array([[1, 2], [1, 3]])
type(a1)

numpy.ndarray

In [4]:
a1.ndim

2

In [5]:
a1.dtype

dtype('int32')

In [6]:
a1.size

4

In [7]:
a1.shape

(2, 2)

# Creating Numpy Arrays From Scratch

## zeros, ones, full, arange, linespace

In [8]:
# zeros
a = np.zeros([2, 3], dtype = 'int').dtype
a

dtype('int32')

In [9]:
b = np.ones([3, 4])
b

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [10]:
# Arange - create np array
c = np.arange(0, 20, 2)
c

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

## Random

In [11]:
# Random
d = np.random.random((4, 6))
d

array([[0.04742765, 0.98762631, 0.30515185, 0.30417173, 0.00352801,
        0.95142805],
       [0.62012469, 0.10286558, 0.97308357, 0.02251906, 0.72430588,
        0.2558015 ],
       [0.3676265 , 0.57070479, 0.20984141, 0.77389444, 0.69576521,
        0.98036516],
       [0.61878446, 0.18633099, 0.80077962, 0.6645305 , 0.06464715,
        0.55074778]])

In [12]:
np.random.rand(4, 5)

array([[0.06373365, 0.6684992 , 0.20237118, 0.9316294 , 0.29478863],
       [0.84361166, 0.17295327, 0.73650818, 0.32691569, 0.20819792],
       [0.4959304 , 0.56646684, 0.37308179, 0.53646907, 0.01842771],
       [0.90804005, 0.55301979, 0.81131585, 0.48358263, 0.4579374 ]])

In [13]:
np.random.normal(0, 1, (3, 2))

array([[ 2.28214271, -0.31060737],
       [-1.16034364, -0.55929193],
       [ 0.81888431,  1.44858781]])

In [14]:
np.random.randint(0, 20, (4, 5))

array([[10,  0, 15,  3, 16],
       [ 7, 12, 13, 18,  4],
       [ 9,  7, 19, 14,  6],
       [ 5, 11,  5,  8,  0]])

# Array Indexing and Slicing

## One-dimensional array

In [15]:
x1 = np.random.randint(20, size=5)
x1

array([13, 15, 10,  2,  7])

In [16]:
x1[4]

7

## Multiple-dimensional array

In [17]:
x2 = np.random.randint(20, size=(3, 4))

In [18]:
x2

array([[ 7,  5,  9, 12],
       [14, 17,  0, 15],
       [16, 15, 15, 10]])

In [19]:
# Step: 2
x1[::2]

array([13, 10,  7])

## Reshaping of Array & Transpose

In [20]:
grid = np.arange(1, 10)

In [21]:
grid

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
grid.reshape((3, 3))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## Array Concatenation and Splitting

In [23]:
x3 = np.array([1, 2, 3])
x4 = np.array([3, 2, 1])
np.concatenate((x3, x4), axis = 0)

array([1, 2, 3, 3, 2, 1])

In [24]:
# Verticle Stack
np.vstack((x3, x4))

array([[1, 2, 3],
       [3, 2, 1]])

In [25]:
np.hstack((x3, x4))

array([1, 2, 3, 3, 2, 1])

## Splitting of array

In [26]:
x = np.array([1, 2, 3, 4 , 5])

In [27]:
np.split(x, [3, 5])

[array([1, 2, 3]), array([4, 5]), array([], dtype=int32)]

## Broadcasting and Vectorised Operation

In [28]:
x + 5

array([ 6,  7,  8,  9, 10])

# Manipulating & Comparing Arrays

### Aggregation

In [29]:
list_number = [1, 2, 3]

massive_array = np.random.random(10000)
massive_array

array([0.81736343, 0.79932989, 0.74111469, ..., 0.4282174 , 0.01364397,
       0.77474688])

In [30]:
%timeit sum(massive_array)
%timeit np.sum(massive_array)

574 µs ± 10.4 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)
16.9 µs ± 3.79 µs per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [31]:
np.mean(massive_array)

0.4976878647108367

In [32]:
np.max(massive_array)

0.9999279488516186

In [33]:
dog_height = [600, 470, 170, 430, 300]
dog_height = np.array(dog_height)
np.std(dog_height)

147.32277488562318

In [34]:
np.var(dog_height)

21704.0

In [35]:
np.sqrt(np.var(dog_height))

147.32277488562318

## Sorting Array

In [36]:
np.sort(dog_height)

array([170, 300, 430, 470, 600])

In [37]:
np.argsort(dog_height)

array([2, 4, 3, 1, 0], dtype=int64)

## Linear Algreba

In [38]:
A = np.array([[1, 2],
               [3, 4],
               [5, 6]])

In [39]:
B = np.array([[1, 2, 3],
               [4, 5, 6]])

In [40]:
A.dot(B)

array([[ 9, 12, 15],
       [19, 26, 33],
       [29, 40, 51]])

In [42]:
A @ B

array([[ 9, 12, 15],
       [19, 26, 33],
       [29, 40, 51]])

In [43]:
B.T # Transpose

array([[1, 4],
       [2, 5],
       [3, 6]])

In [44]:
B.T @ A

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 3 is different from 2)

## Dot Product

In [51]:
np.random.seed(10)

X1 = np.random.randint(20, size=(5, 3))

In [52]:
X1

array([[ 9,  4, 15],
       [ 0, 17, 16],
       [17,  8,  9],
       [ 0, 10,  8],
       [ 4, 19, 16]])

In [56]:
# Create data frame
import pandas as pd
df = pd.DataFrame(X1, index=["Mon", "Tue", "Wed", "Thu", "Fri"], columns=["A1", "A2", "A3"])

In [68]:
df

A1  A2  A3
Mon   9   4  15
Tue   0  17  16
Wed  17   8   9
Thu   0  10   8
Fri   4  19  16

In [69]:
prices = np.array([2, 3, 5])

In [70]:
prices

array([2, 3, 5])

In [71]:
df_prices = pd.DataFrame(prices.reshape(1, 3), index=["Price"], columns=["X1", "X2", "X3"])

In [72]:
df_prices

X1  X2  X3
Price   2   3   5

In [79]:
(df.shape, df_prices.T.shape)

((5, 3), (3, 1))

In [80]:
total_prices = df.dot(df_prices.T)

ValueError: matrices are not aligned

In [81]:
df["total_price"] = total_prices
df

NameError: name 'total_prices' is not defined

In [ ]:
# np.corrcoef()